# Numpy Assignment

**Consider the below code to answer further questions:**

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
import numpy as np

In [3]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
list_

['1', '2', '3', '4', '5']

In [4]:
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

##### Yes, there is a difference in the data type of variables list_ and array_list. The data type of list_ is list while array_list is of numpy array data type (numpy.ndarray)

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [7]:
for i in list_:
    print(f'{i} is of {type(i)} data type.')

1 is of <class 'str'> data type.
2 is of <class 'str'> data type.
3 is of <class 'str'> data type.
4 is of <class 'str'> data type.
5 is of <class 'str'> data type.


In [8]:
for i in array_list:
    print(f'{i} is of {type(i)} data type.')

1 is of <class 'numpy.str_'> data type.
2 is of <class 'numpy.str_'> data type.
3 is of <class 'numpy.str_'> data type.
4 is of <class 'numpy.str_'> data type.
5 is of <class 'numpy.str_'> data type.


### Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int)

##### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [9]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

#### No, there won't any difference in the data type because it is still a numpy array but the data type of the elemnets of the will change from string to int data type.

In [12]:
type(array_list)

numpy.ndarray

In [13]:
for i in array_list:
    print(f'{i} data type is {type(i)}.')

1 data type is <class 'numpy.int32'>.
2 data type is <class 'numpy.int32'>.
3 data type is <class 'numpy.int32'>.
4 data type is <class 'numpy.int32'>.
5 data type is <class 'numpy.int32'>.


**Consider the below code to answer further questions:**

**import numpy as np**

**num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]**

**num_array = np.array(object = num_list)**

### Q4. Write a code to find the following characteristics of variable, num_array:

#### (i)	 shape

#### (ii) size

In [15]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
num_array.shape

(2, 3)

In [17]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
q5 = np.zeros((3,3))
q5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
q5.size

9

In [20]:
q5.shape

(3, 3)

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])